Recuperation_donnees_CKAN/Recuperation/urls.py
from django.urls import path
from .views import statistiquesView

app_name = 'Recuperation'

urlpatterns = [
    path('statistiques/', statistiquesView, name='statistiques'), 
]

Recuperation_donnees_CKAN/Recuperation_donnees_CKAN/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken import views
from Recuperation.views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', homeView, name='home'),
    path('api/', include("api.urls", namespace="api")),
	path('gql/', include("gql.urls", namespace="gql")),
	path('Recuperation/', include("Recuperation.urls", namespace="Recuperation")),
	path('api/token/', views.obtain_auth_token),
]

Recuperation_donnees_CKAN/api/urls.py
from django.urls import path
from .views import EtablissementAPIView, EtablissementDeleteAPIView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="API Établissement Scolaire publique francophone de la ville de Québec",
        default_version='v1',
        description="API de documentaion sur les écoles de la ville de Québec francophone et publique"
    ),
    public=True,
)


urlpatterns = [
    path('ecole/', EtablissementAPIView.as_view(), name = 'ecole_api'),
    path('ecole/<int:etablissement_id>/', EtablissementDeleteAPIView.as_view(), name = 'ecole_api_delete'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

Recuperation_donnees_CKAN/gql/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

app_name = 'gql'

urlpatterns = [
	path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True)), name="gql"),
]

Recuperation_donnees_CKAN/Recuperation/models.py
from django.db import models

# Create your models here.
from django.db import models

class Etablissement(models.Model):
    id = models.AutoField(primary_key=True)
    codeOrg = models.IntegerField()
    codeImm = models.IntegerField()
    nom = models.CharField(max_length = 100)
    coordonnee = models.ForeignKey("Coordonnee", on_delete=models.CASCADE)
    prescolaire = models.BooleanField()
    primaire = models.BooleanField()
    secondaire = models.BooleanField()
    professionnel = models.BooleanField()
    adulte  = models.BooleanField()
    type = models.CharField(max_length = 50)
    ide = models.ForeignKey("IDE", on_delete=models.SET_NULL, null = True, blank=True)
    regroupement = models.ForeignKey("Regroupement", on_delete=models.CASCADE)


class Regroupement(models.Model):

    id = models.AutoField(primary_key=True)
    code = models.IntegerField()
    nom = models.CharField(max_length = 100)
    nom_court = models.CharField(max_length = 50)
    coordonnee = models.ForeignKey("Coordonnee", on_delete=models.CASCADE)
    superficie = models.IntegerField()
    perimetre = models.IntegerField()
    langue = models.CharField(max_length=3)

#Terminee

class IMSE(models.Model):
    id = models.AutoField(primary_key=True)
    indice = models.FloatField()
    rang = models.IntegerField() 
    
class SFR(models.Model):
    id = models.AutoField(primary_key=True)
    indice = models.FloatField()
    rang = models.IntegerField() 

class IDE(models.Model) :
    id = models.AutoField(primary_key=True)
    sfr = models.OneToOneField("SFR", on_delete=models.CASCADE)
    imse = models.OneToOneField("IMSE", on_delete=models.CASCADE)
    defavorisation = models.BooleanField()

class Coordonnee(models.Model):
    id = models.AutoField(primary_key=True)
    adresse = models.CharField(max_length = 100)
    municipalite = models.CharField(max_length = 20)
    code_postal = models.CharField(max_length = 7)
    site = models.URLField(null=True, blank=True)
    telephone = models.CharField(max_length=12, null=True, blank=True)
    

Recuperation_donnees_CKAN/gql/models.py
from django.db import models

# Create your models here.

Recuperation_donnees_CKAN/Recuperation/views.py
from django.shortcuts import render
from .dataImport import Stats

# Create your views here.
def homeView(request):
	return render(request, "home.html")

def statistiquesView(request):
	stats = Stats()
	return render(request, "Recuperation/statistiques.html", {"stats": stats})

Recuperation_donnees_CKAN/api/views.py
from rest_framework.views import APIView, status, Response
from Recuperation.models import Etablissement
from .serializers import EtablissementSerializer
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from rest_framework.permissions import IsAuthenticated


class EtablissementAPIView(APIView):
    permission_classes = [ IsAuthenticated ]
    @swagger_auto_schema(tags=['Etablissements'],
    operation_description="Récupérer toutes les écoles",
    responses= {200 : EtablissementSerializer(many=True)})
    def get(self, request):
        etablissements = Etablissement.objects.all()
        etablissements_serializer = EtablissementSerializer(etablissements, many=True)
        return Response(etablissements_serializer.data, status = status.HTTP_200_OK)
    
    @swagger_auto_schema(
        tags=['Etablissements'],
        operation_description="Ajouter une école",
        request_body=EtablissementSerializer, 
        responses= {
            201 : EtablissementSerializer, # Affichera l'objet créé en cas de succès
            400 : "Bad Request"
        }
    )
    def post(self, request):
        etablissements_serializer = EtablissementSerializer(data=request.data)
        if etablissements_serializer.is_valid():
            etablissements_serializer.save()
            return Response({"message" : "Valide"}, status = status.HTTP_201_CREATED)
        else:
           return Response(etablissements_serializer.errors, status = status.HTTP_400_BAD_REQUEST)



class EtablissementDeleteAPIView(APIView):    
    permission_classes = [ IsAuthenticated ]

    @swagger_auto_schema(
        tags=['Etablissements'],
        operation_description="Supprimé une école par son ID",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "id": openapi.Schema(
                    type=openapi.TYPE_INTEGER,
                    description="ID de l'école à supprimer",
                )
            },
            required=["id"], 
        ),
        responses= {204 : "Établissement supprimé", 404:"Not Found"}
    )

    def delete(self, request, etablissement_id):
        try:
            etablissement = Etablissement.objects.get(id=etablissement_id)
        except: 
            return Response({"error" : "Établissement non trouvé"}, status = status.HTTP_404_NOT_FOUND)

        etablissement.delete()
        return Response({"message" : "Établissement supprimée"}, status = status.HTTP_204_NO_CONTENT)

Recuperation_donnees_CKAN/gql/views.py
from django.shortcuts import render

# Create your views here.

Recuperation_donnees_CKAN/templates/Recuperation/statistiques.html
{% extends "base.html" %}

{% block title %}Statistiques CKAN{% endblock %}

{% block content %}
	<div class="mb-4">
		<h1>Statistiques CKAN</h1>
		<h2>Liste des sources</h2>
		{% for url in stats.urls %}
			<div class="row row-cols-1 row-cols-md-1 g-4">
				<div class="col">
					<div class="card text-white bg-success mb-3">
						<div class="card-body">
							<h5 class="card-title">Source {{ forloop.counter }}:</h5>
							<p class="card-text">{{ url }}</p>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<hr>
	<div class="mb-4">
		<h2>Statistiques sur la base de données:</h2>
		<div class ="row row-cols-1 row-cols-md-3 g-4">
			<div class="col">
				<div class="card text-white bg-primary mb-3">
					<div class="card-body">
						<h5 class="card-title">Jeux de données</h5>
						<p class="card-text">{{ stats.get_total_datasets }}</p>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card text-white bg-success mb-3">
					<div class="card-body">
						<h5 class="card-title">Écoles</h5>
						<p class="card-text">{{ stats.get_total_ecoles }}</p>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card text-white bg-danger mb-3">
					<div class="card-body">
						<h5 class="card-title">Centres de services scolaires</h5>
						<p class="card-text">{{ stats.get_total_regroupements }}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row row-cols-1 row-cols-md-2 g-4">
			<div class="col">
				<div class="card text-white bg-warning mb-3">
					<div class="card-body">
						<h5 class="card-title">Indices de défavorisation</h5>
						<p class="card-text">{{ stats.get_total_IDEs }}</p>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card text-white bg-info mb-3">
					<div class="card-body">
						<h5 class="card-title">Écoles défavorisées</h5>
						<p class="card-text">{{ stats.get_total_ecoles_defavorisees }}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row row-cols-1 row-cols-md-1 g-4">
			<div class="col">
				<div class="card text-white bg-secondary mb-3">
					<div class="card-body">
						<h5 class="card-title">Écoles par centre de services scolaires</h5>
						<p class="card-text">
							<ul>
								{% for reg, count in stats.get_ecole_par_regroupement.items %}
									<li>{{ reg }}: {{ count }}</li>
								{% endfor %}
							</ul>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

Recuperation_donnees_CKAN/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Recuperation Donnees CKAN{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
		{% block head %}{% endblock %}
	</head>
	<body>
		{% block nav %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
			<a class="navbar-brand" href="{% url 'home' %}">CKAN</a>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'api:schema-swagger-ui' %}">Swagger</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'gql:gql' %}">API GraphQL</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'Recuperation:statistiques' %}">Statistiques</a>
					</li>
				</ul>
			</div>
		</nav>
		{% endblock %}
		{% block body %}

			{% block content %}{% endblock %}

		{% endblock %}
	</body>
</html>

Recuperation_donnees_CKAN/templates/home.html
{% extends "base.html" %}

{% block title %}Accueil - CKAN{% endblock %}

{% block content %}
	<div class="container">
		<div class="row mb-4">
			<div class="col">
				<h1>Bienvenue sur l'api de récupération de données CKAN</h1>
				<h5>Utilisez le menu du haut pour naviguer dans les différentes sections.</h5>
			</div>
		</div>
	</div>
{% endblock %}